/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.apache.commons.mail.resolver;

import static org.junit.Assert.*;

import org.apache.commons.mail.DataSourceResolver;
import org.evosuite.runtime.EvoAssertions;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.evosuite.runtime.mock.java.net.MockURL;
import org.evosuite.runtime.testdata.EvoSuiteURL;
import org.evosuite.runtime.testdata.NetworkHandling;
import org.evosuite.shaded.org.mockito.Mockito;
import org.evosuite.shaded.org.mockito.exceptions.base.MockitoException;
import org.junit.Assert;
import org.junit.Test;

import javax.activation.DataSource;
import java.io.File;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.net.URLStreamHandler;

/**
 * JUnit test case for DataSourceUrlResolver.
 *
 * @since 1.3
 */
public class DataSourceUrlResolverTest extends AbstractDataSourceResolverTest
{

    /**
     * Shows how the DataSourceUrlResolver can resolve files as well but this should
     * be done using a DataSourceFileResolver.
     *
     * @throws Exception the test failed
     */
    @Test
    public void testResolvingFilesLenient() throws Exception
    {
        final DataSourceResolver dataSourceResolver = new DataSourceUrlResolver(new File("./src/test/resources").toURI().toURL(), true);
        assertEquals(IMG_SIZE, toByteArray(dataSourceResolver.resolve("images/asf_logo_wide.gif")).length);
        assertEquals(IMG_SIZE, toByteArray(dataSourceResolver.resolve("./images/asf_logo_wide.gif")).length);
        assertNull(dataSourceResolver.resolve("./images/does-not-exist.gif"));
        assertNull(dataSourceResolver.resolve("/images/asf_logo_wide.gif"));
    }

    /**
     * Tests resolving resources over HTTP.
     *
     * @throws Exception the test failed
     */
    @Test
    public void testResolvingHttpLenient() throws Exception
    {
        final DataSourceResolver dataSourceResolver = new DataSourceUrlResolver(new URL("https://www.apache.org"), true);
        assertTrue(toByteArray(dataSourceResolver.resolve("https://www.apache.org/images/feather-small.gif")).length > 1);
        assertTrue(toByteArray(dataSourceResolver.resolve("images/feather-small.gif")).length > 1);
        assertTrue(toByteArray(dataSourceResolver.resolve("./images/feather-small.gif")).length > 1);
        assertTrue(toByteArray(dataSourceResolver.resolve("/images/feather-small.gif")).length > 1);
    }

    /**
     * Tests resolving resources over HTTP.
     *
     * @throws Exception the test failed
     */
    @Test
    public void testResolvingHttpLenientHost() throws Exception
    {
        final DataSourceResolver dataSourceResolver = new DataSourceUrlResolver(new URL("http://does.not.exist"), true);
        assertNull(toByteArray(dataSourceResolver.resolve("/images/does-not-exist.gif")));
    }

    /**
     * Tests resolving resources over HTTP.
     *
     * @throws Exception the test failed
     */
    @Test(expected = IOException.class)
    public void testResolvingHttpNonLenient() throws Exception
    {
        final DataSourceResolver dataSourceResolver = new DataSourceUrlResolver(new URL("http://does.not.exist"), false);
        assertNotNull(dataSourceResolver.resolve("images/asf_logo_wide.gif"));

        dataSourceResolver.resolve("images/does-not-exist.gif");
    }



    //Test Generated by EvoSuite
    @Test
    public void test00() throws Throwable {
        //URL var1 = MockURL.getHttpExample();
        //EvoSuiteURL var2 = new EvoSuiteURL("http://www.someFakeButWellFormedURL.org/C");
        //NetworkHandling.createRemoteTextFile(var2, ",Y'__|eQGxw&#$O");
        DataSourceUrlResolver var3 = new DataSourceUrlResolver(new URL("https://www.apache.org"), false);
        DataSource var4 = var3.resolve("images/feather-small.gif", true);
        Assert.assertNotNull(var4);
    }

    //Test rimosso perché ha lo stesso comportamento del test00
    /*@Test
    public void test01() throws Throwable {
        URL var1 = MockURL.getHttpExample();
        EvoSuiteURL var2 = new EvoSuiteURL("http://www.someFakeButWellFormedURL.org/C");
        NetworkHandling.createRemoteTextFile(var2, ",Y'__|eQGxw&#$O");
        DataSourceUrlResolver var3 = new DataSourceUrlResolver(var1, false);
        DataSource var4 = var3.resolve("C");
        Assert.assertNotNull(var4);
    }*/

    @Test
    public void test02() throws Throwable {
        DataSourceUrlResolver var1 = new DataSourceUrlResolver((URL)null);
        URL var2 = var1.getBaseUrl();
        Assert.assertNull(var2);
    }

    //Test commentati perché si cerca di fare il mock di classi astratte
   /* @Test(
            expected = MockitoException.class
    )
    public void test03() throws Throwable {
        URLStreamHandler var1 = (URLStreamHandler) Mockito.mock(URLStreamHandler.class, new ViolatedAssumptionAnswer());
        URL var2 = MockURL.URL("`d]", "", 0, "`d]", var1);
        DataSourceUrlResolver var3 = new DataSourceUrlResolver(var2, true);
        URL var4 = var3.getBaseUrl();
        Assert.assertEquals("`d]", var4.getPath());
    }

    @Test(
            expected = MockitoException.class
    )
    public void test04() throws Throwable {
        URLStreamHandler var1 = (URLStreamHandler)Mockito.mock(URLStreamHandler.class, new ViolatedAssumptionAnswer());
        URL var2 = MockURL.URL("pf5ps4A>-AD0)Tz=", "dH;E&", 3656, "pf5ps4A>-AD0)Tz=", var1);
        DataSourceUrlResolver var3 = new DataSourceUrlResolver(var2);
        URL var4 = var3.getBaseUrl();
        Assert.assertEquals("pf5ps4a>-ad0)tz=", var4.getProtocol());
    }

    @Test(
            expected = MockitoException.class
    )
    public void test05() throws Throwable {
        URL var1 = MockURL.getFtpExample();
        URLStreamHandler var2 = (URLStreamHandler)Mockito.mock(URLStreamHandler.class, new ViolatedAssumptionAnswer());
        URL var3 = MockURL.URL(var1, "", var2);
        DataSourceUrlResolver var4 = new DataSourceUrlResolver(var3);
        URL var5 = var4.getBaseUrl();
        Assert.assertSame(var3, var5);
    }
*/
    @Test
    public void test06() throws Throwable {
        URL var1 = MockURL.getHttpExample();
        DataSourceUrlResolver var2 = new DataSourceUrlResolver(var1, false);
        URL var3 = var2.createUrl("\u007f_6b|J2kOOn@`");
        Assert.assertEquals("http://www.someFakeButWellFormedURL.org/\u007f_6b|J2kOOn@`", var3.toExternalForm());
    }

    @Test
    public void test07() throws Throwable {
        DataSourceUrlResolver var1 = new DataSourceUrlResolver((URL)null);

        try {
            var1.resolve("?x8Uv", false);
            Assert.fail("Expecting exception: MalformedURLException");
        } catch (MalformedURLException var3) {
            EvoAssertions.verifyException("java.net.URL", var3);
        }

    }

    //Si aspetta che il test da NullPointerException ma non è così
   /* @Test
    public void test08() throws Throwable {
        URL var1 = MockURL.getHttpExample();
        DataSourceUrlResolver var2 = new DataSourceUrlResolver(var1);

        try {
            var2.resolve("file:/", true);
            Assert.fail("Expecting exception: NullPointerException");
        } catch (NullPointerException var4) {
            EvoAssertions.verifyException("java.net.URL", var4);
        }

    }*/

    @Test
    public void test09() throws Throwable {
        URL var1 = MockURL.getHttpExample();
        DataSourceUrlResolver var2 = new DataSourceUrlResolver(var1);

        try {
            var2.resolve("", false);
            Assert.fail("Expecting exception: IllegalArgumentException");
        } catch (IllegalArgumentException var4) {
            EvoAssertions.verifyException("org.apache.commons.mail.resolver.DataSourceUrlResolver", var4);
        }

    }

    @Test
    public void test10() throws Throwable {
        URL var1 = MockURL.getFtpExample();
        DataSourceUrlResolver var2 = new DataSourceUrlResolver(var1);

        try {
            var2.resolve("ie:/");
            Assert.fail("Expecting exception: MalformedURLException");
        } catch (MalformedURLException var4) {
            EvoAssertions.verifyException("java.net.URL", var4);
        }

    }

    @Test
    public void test11() throws Throwable {
        DataSourceUrlResolver var1 = new DataSourceUrlResolver((URL)null);

        try {
            var1.createUrl("org.apache.commons.mail.resolver.DataSourceUrlResolver");
            Assert.fail("Expecting exception: MalformedURLException");
        } catch (MalformedURLException var3) {
            EvoAssertions.verifyException("java.net.URL", var3);
        }

    }

    @Test(expected = IOException.class)
    public void test12() throws Throwable {
        //URL var1 = MockURL.getHttpExample();
        URL var1 =new URL("https://www.apache.org");
        DataSourceUrlResolver var2 = new DataSourceUrlResolver(var1, false);

     //  try {
            var2.resolve("*#u\u007fl}O~C7+Qmm^#4;v", false);
            //var2.resolve("https://", false);
            Assert.fail("Expecting exception: IOException");
       /* } catch (IOException var4) {
            System.out.println("Sono nel catch");
            //EvoAssertions.verifyException("org.evosuite.runtime.mock.java.net.EvoHttpURLConnection", var4);
        }*/

    }

    @Test
    public void test13() throws Throwable {
        URL var1 = MockURL.getFtpExample();
        DataSourceUrlResolver var2 = new DataSourceUrlResolver(var1);
        DataSource var3 = var2.resolve("cid:", true);
        Assert.assertNull(var3);
    }

    @Test(
            expected = IOException.class)
    public void test14() throws Throwable {
        //URL var1 = MockURL.getFileExample();
        URL var1 =new URL("https://www.apache.org");
        DataSourceUrlResolver var2 = new DataSourceUrlResolver(var1);

        //try {
            var2.resolve("*#u\u007fl}O~C7+Qmm^#4;v");
            Assert.fail("Expecting exception: IOException");
        /*} catch (IOException var4) {
            EvoAssertions.verifyException("org.evosuite.runtime.mock.java.net.EvoHttpURLConnection", var4);
        }*/

    }
    //Si aspetta che il test da NullPointerException ma non è così
    /*
    @Test
    public void test15() throws Throwable {
        URL var1 = MockURL.getFtpExample();
        DataSourceUrlResolver var2 = new DataSourceUrlResolver(var1);

        try {
            var2.resolve("file:/");
            Assert.fail("Expecting exception: NullPointerException");
        } catch (NullPointerException var4) {
            EvoAssertions.verifyException("java.net.URL", var4);
        }

    }*/

    @Test
    public void test16() throws Throwable {
        URL var1 = MockURL.getFileExample();
        DataSourceUrlResolver var2 = new DataSourceUrlResolver(var1, true);

        try {
            var2.resolve("");
            Assert.fail("Expecting exception: IllegalArgumentException");
        } catch (IllegalArgumentException var4) {
            EvoAssertions.verifyException("org.apache.commons.mail.resolver.DataSourceUrlResolver", var4);
        }

    }

    @Test
    public void test17() throws Throwable {
        DataSourceUrlResolver var1 = new DataSourceUrlResolver((URL)null);
        DataSource var2 = var1.resolve("KJ@1\"T{", true);
        Assert.assertNull(var2);
    }

    @Test
    public void test18() throws Throwable {
        URL var1 = MockURL.getFileExample();
        DataSourceUrlResolver var2 = new DataSourceUrlResolver(var1);
        DataSource var3 = var2.resolve("cid:");
        Assert.assertNull(var3);
    }

    @Test
    public void test19() throws Throwable {
        URL var1 = MockURL.getFtpExample();
        DataSourceUrlResolver var2 = new DataSourceUrlResolver(var1);

        try {
            var2.createUrl((String)null);
            Assert.fail("Expecting exception: IllegalArgumentException");
        } catch (IllegalArgumentException var4) {
            EvoAssertions.verifyException("org.apache.commons.mail.resolver.DataSourceUrlResolver", var4);
        }

    }

    @Test
    public void test20() throws Throwable {
        URL var1 = MockURL.getHttpExample();
        DataSourceUrlResolver var2 = new DataSourceUrlResolver(var1, false);
        URL var3 = var2.getBaseUrl();
        Assert.assertEquals("http://www.someFakeButWellFormedURL.org/fooExample", var3.toString());
    }


}
